import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { active, canStart, Item, Kind, Priority, recommendation, Status } from './domain';
import { isSupabaseConfigured, supabase } from './supabase';

const today = new Date().toISOString().slice(0, 10);
const make = (title:string, status:Status, extra:Partial<Item> = {}):Item => ({id: crypto.randomUUID(), title, status, kind:'TASK', priority:'NORMAL', events:[{id:crypto.randomUUID(),at:new Date().toISOString(),action:'Creado'}],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...extra});
const seed: Item[] = [
 make('Negociar compra Michelin','ACTIVE',{kind:'PROJECT',role:'Compras',priority:'HIGH',dueDate:today,nextAction:'Llamar al proveedor y confirmar bonificación.',progress:60}),
 make('Aprobar campaña WhatsApp','ACTIVE',{role:'Marketing',priority:'HIGH',dueDate:today,nextAction:'Aprobar las tres publicaciones pendientes.'}),
 make('Revisar cartera con Sol','NEXT',{role:'CEO / Dirección General',priority:'HIGH',nextAction:'Revisar los diez clientes con mayor cartera vencida.'}),
 make('Diferencias de inventario','BLOCKED',{role:'CEO / Dirección General',priority:'HIGH',person:'Azucena Hernández',blocker:'Espero información',reviewDate:today,nextAction:'Revisar conciliación física contra sistema.'}),
 make('Análisis de cartera','WAITING',{person:'Sol Ángel Cruz',dueDate:today,reviewDate:today,priority:'HIGH'}),
 make('Revisar resultados Matriz','WAITING',{person:'Moisés Pérez',reviewDate:today}),
 make('Analizar nueva sucursal','SOMEDAY',{kind:'IDEA',role:'CEO / Dirección General'}),
 make('Renovar contrato de seguro','INBOX')
];
const labels:Record<Status,string>={INBOX:'Bandeja',NEXT:'Próximos',ACTIVE:'En curso',BLOCKED:'Bloqueados',SOMEDAY:'Algún día',DONE:'Terminados',CANCELLED:'Cancelados',WAITING:'Esperando'};
const priorities:Priority[]=['CRITICAL','HIGH','NORMAL','LOW'];

export default function App(){
 const [items,setItems]=useState<Item[]>(()=>JSON.parse(localStorage.getItem('mi-carril-items')||'null')||seed);
 const backupInput=useRef<HTMLInputElement>(null);
 const [screen,setScreen]=useState('Inicio'); const [capture,setCapture]=useState(false); const [draft,setDraft]=useState(''); const [selected,setSelected]=useState<Item|null>(null); const [message,setMessage]=useState('');
 const [session,setSession]=useState<Session|null>(null); const [authChecked,setAuthChecked]=useState(!isSupabaseConfigured); const [cloudReady,setCloudReady]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthChecked(true);});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{if(!supabase||!session)return;let live=true;supabase.from('items').select('data').order('updated_at',{ascending:false}).then(({data,error})=>{if(!live)return;if(error){setMessage('No fue posible cargar la nube. Conservamos tu copia local.');return;}const cloudItems=(data||[]).map(row=>row.data as Item);if(cloudItems.length)setItems(cloudItems);setCloudReady(true);});return()=>{live=false;};},[session]);
 const save=(next:Item[])=>{setItems(next);localStorage.setItem('mi-carril-items',JSON.stringify(next));if(supabase&&session&&cloudReady){const rows=next.map(item=>({id:item.id,owner_id:session.user.id,created_by:session.user.id,assigned_to:null,visibility:item.visibility==='SHARED'?'shared':item.visibility==='COACH_ASSIGNED'?'coach_assigned':'personal',title:item.title,status:item.status,data:item}));supabase.from('items').upsert(rows,{onConflict:'id'}).then(({error})=>{if(error)setMessage('Tu cambio quedó guardado localmente, pero aún no llegó a la nube.');});}};
 const update=(id:string, patch:Partial<Item>, action:string, note?:string)=>save(items.map(i=>i.id===id?{...i,...patch,updatedAt:new Date().toISOString(),events:[...i.events,{id:crypto.randomUUID(),at:new Date().toISOString(),action,note}]}:i));
 const start=(item:Item)=>{if(!item.nextAction?.trim()) return setMessage('Define qué acción concreta mueve este asunto hacia adelante.'); if(!canStart(items,item)) return setMessage('Ya tienes 3 asuntos activos en tu carril. Este asunto permanece en Próximo.'); update(item.id,{status:'ACTIVE'},'Pasó a EN CURSO');};
 const lanes=active(items); const alerts=items.filter(i=>(i.dueDate&&i.dueDate<=today&&i.status!=='DONE')||(i.reviewDate&&i.reviewDate<=today&&['BLOCKED','WAITING'].includes(i.status)));
 const rec=useMemo(()=>recommendation(items),[items]);
 const filtered=screen==='Inicio'?[]:items.filter(i=>labels[i.status]===screen || (screen==='Proyectos'&&i.kind==='PROJECT'));
 const backup=()=>{const blob=new Blob([JSON.stringify({format:'mi-carril-export',schemaVersion:1,appVersion:'0.1.0',exportedAt:new Date().toISOString(),items},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`mi-carril-respaldo-${today}.json`;link.click();URL.revokeObjectURL(url);setMessage('Respaldo descargado. Tus datos permanecen también en este dispositivo.');};
 const restore=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));if(data.format!=='mi-carril-export'||data.schemaVersion!==1||!Array.isArray(data.items))throw new Error();if(!confirm(`Restaurar ${data.items.length} asuntos reemplazará la copia de este dispositivo. ¿Ya tienes un respaldo reciente?`))return;save(data.items);setMessage('Respaldo restaurado correctamente.');}catch{setMessage('El archivo no parece ser un respaldo válido de Mi Carril.');}};reader.readAsText(file);event.target.value='';};
 const closeDetail=()=>setSelected(null);
 if(!authChecked)return <div className="authpage"><p>Preparando Mi Carril…</p></div>;
 if(isSupabaseConfigured&&!session)return <SignIn/>;
 return <div className="shell"><aside><div className="brand">mi carril<span>ejecuta con claridad</span></div>{['Inicio','Mi Carril','Bandeja','Próximos','Esperando','Bloqueados','Proyectos','Algún día','Terminados'].map(x=><button className={screen===x?'nav on':'nav'} onClick={()=>setScreen(x)} key={x}>{x}</button>)}<button className="nav" onClick={()=>setScreen('Métricas')}>Métricas</button></aside>
 <main><header><div><p className="eyebrow">Sábado, 16 de agosto</p><h1>{screen}</h1></div><div className="headeractions">{session&&<button className="backup" onClick={()=>supabase?.auth.signOut()}>SALIR</button>}<button className="backup" onClick={backup}>RESPALDAR</button><button className="backup" onClick={()=>backupInput.current?.click()}>RESTAURAR</button><input ref={backupInput} className="hidden" type="file" accept="application/json" onChange={restore}/><button className="capture" onClick={()=>setCapture(true)}>+ CAPTURAR</button></div></header>
 {message&&<div className="toast" onClick={()=>setMessage('')}>{message}</div>}
 {screen==='Inicio'&&<><section className="focus"><p>¿QUÉ HAGO AHORA?</p>{rec?<><h2>{rec.title}</h2><span>Porque {rec.dueDate===today?'vence hoy':'es la prioridad más relevante de tu carril'} y está marcado como prioridad {rec.priority.toLowerCase()}.</span><strong>Siguiente acción: {rec.nextAction||'Define la siguiente acción.'}</strong><button onClick={()=>{start(rec);setScreen('Mi Carril')}}>EMPEZAR</button></>:<p>No tienes prioridades activas.</p>}</section><div className="grid four"><Stat n={lanes.length} t="En mi carril"/><Stat n={items.filter(i=>i.status==='INBOX').length} t="Sin procesar"/><Stat n={items.filter(i=>i.status==='BLOCKED').length} t="Bloqueados"/><Stat n={items.filter(i=>i.status==='WAITING').length} t="Esperando"/></div><section><h2>Requieren atención</h2>{alerts.length?alerts.map(i=><Card key={i.id} item={i} onClick={()=>setSelected(i)}/>):<Empty text="Todo está bajo control por ahora."/>}</section></>}
 {screen==='Mi Carril'&&<><p className="intro">Solo tres asuntos pueden ocupar tu atención activa.</p><div className="lanes">{[0,1,2].map((n)=><div className="lane" key={n}><span>{n===0?'1 — AHORA':`${n+1} — DESPUÉS`}</span>{lanes[n]?<Card item={lanes[n]} onClick={()=>setSelected(lanes[n])}/>:<Empty text="Espacio disponible. Elige algo que merezca entrar."/>}</div>)}</div></>}
 {screen==='Métricas'&&<div className="grid four"><Stat n={items.filter(i=>i.status==='DONE').length} t="Terminados"/><Stat n={items.filter(i=>i.status==='DONE'&&(!i.dueDate||i.updatedAt.slice(0,10)<=i.dueDate)).length} t="A tiempo"/><Stat n={alerts.length} t="Alertas"/><Stat n={items.filter(i=>i.kind==='PROJECT'&&i.status==='ACTIVE').length} t="Proyectos activos"/></div>}
 {!['Inicio','Mi Carril','Métricas'].includes(screen)&&<section><p className="intro">{filtered.length} elemento{filtered.length===1?'':'s'}</p>{filtered.length?filtered.map(i=><Card item={i} key={i.id} onClick={()=>setSelected(i)}/>):<Empty text={`${screen} procesada. Nada necesita tu atención aquí.`}/>}</section>}
 </main>{capture&&<Capture onCancel={()=>setCapture(false)} onSave={()=>{if(draft.trim()){save([...items,make(draft.trim(),'INBOX')]);setDraft('');setCapture(false);setMessage('Guardado. Ya no necesitas recordarlo.')}}} draft={draft} setDraft={setDraft}/>} {selected&&<Detail item={items.find(i=>i.id===selected.id)!} onClose={closeDetail} onUpdate={update} onStart={start}/>}</div>
}
function Stat({n,t}:{n:number,t:string}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Card({item,onClick}:{item:Item,onClick:()=>void}){return <button className="card" onClick={onClick}><div><small>{item.role||labels[item.status]} · {item.priority}</small><h3>{item.title}</h3>{item.nextAction&&<p>{item.nextAction}</p>}</div><div className="meta">{item.progress!==undefined&&<b>{item.progress}%</b>}{item.dueDate&&<span>{item.dueDate===today?'Vence hoy':`Vence ${item.dueDate}`}</span>}</div></button>}
function Capture({draft,setDraft,onCancel,onSave}:{draft:string;setDraft:(x:string)=>void;onCancel:()=>void;onSave:()=>void}){return <div className="overlay"><div className="modal capturemodal"><button className="close" onClick={onCancel}>×</button><p className="eyebrow">CAPTURA RÁPIDA</p><h2>¿Qué tienes en la cabeza?</h2><textarea autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Ej. Revisar diferencias de inventario con Azucena."/><button className="primary" onClick={onSave}>GUARDAR EN BANDEJA</button></div></div>}
function SignIn(){const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [error,setError]=useState('');const send=async()=>{if(!supabase||!email.trim())return;const {error:loginError}=await supabase.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:window.location.href}});if(loginError)setError(loginError.message);else setSent(true);};return <div className="authpage"><div className="authcard"><div className="brand dark">mi carril<span>ejecuta con claridad</span></div><h1>Tu sistema de ejecución</h1>{sent?<p>Revisa tu correo y abre el enlace de acceso. Después volverás automáticamente a Mi Carril.</p>:<><p>Inicia sesión para conservar tus pendientes, usarlos desde cualquier dispositivo y controlar quién puede verlos.</p><label>Tu correo<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@correo.com"/></label>{error&&<p className="autherror">{error}</p>}<button className="primary" onClick={send}>ENVIAR ENLACE DE ACCESO</button></>}</div></div>}
function Detail({item,onClose,onUpdate,onStart}:{item:Item;onClose:()=>void;onUpdate:(id:string,p:Partial<Item>,a:string,n?:string)=>void;onStart:(i:Item)=>void}){const [next,setNext]=useState(item.nextAction||''); const [review,setReview]=useState(item.reviewDate||today); const [note,setNote]=useState(''); const process=(status:Status)=>onUpdate(item.id,{status,nextAction:next||undefined},`Procesado: ${labels[status]}`); return <div className="overlay"><div className="modal"><button className="close" onClick={onClose}>×</button><small>{labels[item.status]} · {item.kind}</small><h2>{item.title}</h2><label>Prioridad<select value={item.priority} onChange={e=>onUpdate(item.id,{priority:e.target.value as Priority},'Prioridad actualizada')} >{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label>Rol<input value={item.role||''} onChange={e=>onUpdate(item.id,{role:e.target.value},'Rol actualizado')}/></label><label>Siguiente acción<input value={next} onChange={e=>setNext(e.target.value)} onBlur={()=>next!==item.nextAction&&onUpdate(item.id,{nextAction:next},'Siguiente acción actualizada')}/></label>{item.status==='INBOX'&&<div className="actions"><button onClick={()=>process('NEXT')}>ENVIAR A PRÓXIMO</button><button onClick={()=>process('SOMEDAY')}>ES IDEA</button></div>}{['NEXT','BLOCKED'].includes(item.status)&&<button className="primary" onClick={()=>onStart({...item,nextAction:next})}>{item.status==='BLOCKED'?'DESBLOQUEAR E INICIAR':'INICIAR EN MI CARRIL'}</button>}{item.status==='ACTIVE'&&<><div className="actions"><button onClick={()=>{onUpdate(item.id,{status:'BLOCKED',reviewDate:review,blocker:'Espero información'},'Bloqueado',note);}}>ESTOY BLOQUEADO</button><button onClick={()=>onUpdate(item.id,{status:'DONE'},'Terminado',note)}>TERMINAR</button></div><label>Fecha para revisar bloqueo<input type="date" value={review} onChange={e=>setReview(e.target.value)}/></label><label>Nota de avance o bloqueo<input value={note} onChange={e=>setNote(e.target.value)}/></label><button onClick={()=>onUpdate(item.id,{progress:item.kind==='PROJECT'?Math.min(100,(item.progress||0)+10):item.progress},'Avance registrado',note)}>AVANCÉ</button></>}{item.kind==='PROJECT'&&<label>Progreso<input type="number" min="0" max="100" value={item.progress??0} onChange={e=>onUpdate(item.id,{progress:Number(e.target.value)},'Progreso actualizado')}/></label>}<h3>Historial</h3><div className="timeline">{[...item.events].reverse().map(e=><p key={e.id}><b>{new Date(e.at).toLocaleString('es-MX')}</b> {e.action}{e.note&&`: ${e.note}`}</p>)}</div></div></div>}
