import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { active, areaLabels, blockerLabels, BlockerCategory, canStart, GameRole, gameRoleLabels, Item, Kind, LifeArea, Priority, recommendation, ReplanReason, replanReasonLabels, Status, timing, timingLabels } from './domain';
import { isSupabaseConfigured, supabase } from './supabase';
import './changes.css';

const today = new Date().toISOString().slice(0, 10);
const make = (title:string, status:Status, extra:Partial<Item> = {}):Item => ({ id:crypto.randomUUID(), title, status, kind:'TASK', priority:'NORMAL', area:'MISSION', visibility:'PERSONAL', events:[{id:crypto.randomUUID(),at:new Date().toISOString(),action:'Creado'}], createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), ...extra });
const seed:Item[]=[
  make('Negociar compra Michelin','ACTIVE',{kind:'PROJECT',gameRole:'QUARTERBACK',role:'Dirección General',priority:'HIGH',dueDate:today,originalDueDate:today,nextAction:'Llamar al proveedor y confirmar bonificación.',progress:60}),
  make('Aprobar campaña WhatsApp','ACTIVE',{gameRole:'REFEREE',role:'Dirección General',priority:'HIGH',dueDate:today,originalDueDate:today,nextAction:'Revisar que las publicaciones cumplan el estándar.'}),
  make('Revisar cartera con Sol','NEXT',{gameRole:'QUARTERBACK',role:'Dirección General',priority:'HIGH',nextAction:'Revisar los diez clientes con mayor cartera vencida.'}),
  make('Diferencias de inventario','BLOCKED',{gameRole:'COACH',role:'Dirección General',priority:'HIGH',person:'Azucena Hernández',blocker:'Falta información para conciliar físico contra sistema.',directManager:'Dirección General',escalatedTo:'Dirección General',escalatedAt:new Date().toISOString(),escalationMethod:'Reunión',escalationMessage:'Se requiere apoyo para definir el criterio de conciliación.',requestedSupport:'Formación y decisión de criterio.',escalationReviewDate:today,reviewDate:today,nextAction:'Revisar conciliación física contra sistema.'}),
  make('Análisis de cartera','WAITING',{person:'Sol Ángel Cruz',dueDate:today,originalDueDate:today,reviewDate:today,priority:'HIGH'}),
  make('Renovar contrato de seguro','INBOX',{area:'FAMILY'}),
];
const labels:Record<Status,string>={INBOX:'Bandeja',NEXT:'Próximos',ACTIVE:'En curso',BLOCKED:'Bloqueados',SOMEDAY:'Algún día',DONE:'Terminados',CANCELLED:'Cancelados',WAITING:'Esperando'};
const priorities:Priority[]=['CRITICAL','HIGH','NORMAL','LOW'];
const kindLabels:Record<Kind,string>={TASK:'Tarea',PROJECT:'Proyecto',FOLLOW_UP:'Acuerdo / seguimiento',MEETING:'Reunión',DECISION:'Decisión',IDEA:'Idea'};
const normalizeItems=(raw:Item[]):Item[]=>raw.map(item=>({...item,area:item.area||'MISSION',visibility:item.visibility||'PERSONAL',events:item.events||[],originalDueDate:item.originalDueDate||item.dueDate}));
const dayAfter=(date:string, amount:number)=>{const value=new Date(`${date}T12:00:00`);value.setDate(value.getDate()+amount);return value.toISOString().slice(0,10)};
type CalendarEntry={item:Item;date:string;mode:'COMPROMISO'|'SEGUIMIENTO'|'REUNION'};
const weekEntries=(items:Item[])=>{const end=dayAfter(today,6);return items.flatMap(item=>{const entries:CalendarEntry[]=[];if(item.dueDate)entries.push({item,date:item.dueDate,mode:'COMPROMISO'});if(item.reviewDate&&item.reviewDate!==item.dueDate)entries.push({item,date:item.reviewDate,mode:'SEGUIMIENTO'});if(item.escalationReviewDate&&item.escalationReviewDate!==item.reviewDate)entries.push({item,date:item.escalationReviewDate,mode:'SEGUIMIENTO'});if(item.meetingAt){const date=item.meetingAt.slice(0,10);if(date!==item.dueDate&&date!==item.reviewDate)entries.push({item,date,mode:'REUNION'});}return entries;}).filter(entry=>!['DONE','CANCELLED'].includes(entry.item.status)&&entry.date>=today&&entry.date<=end).sort((a,b)=>a.date.localeCompare(b.date));};

export default function App(){
 const [items,setItems]=useState<Item[]>(()=>normalizeItems(JSON.parse(localStorage.getItem('mi-carril-items')||'null')||seed));
 const backupInput=useRef<HTMLInputElement>(null); const [screen,setScreen]=useState('Comando'); const [capture,setCapture]=useState(false); const [draft,setDraft]=useState(''); const [selected,setSelected]=useState<Item|null>(null); const [message,setMessage]=useState('');
 const [session,setSession]=useState<Session|null>(null); const [authChecked,setAuthChecked]=useState(!isSupabaseConfigured); const [cloudReady,setCloudReady]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthChecked(true);});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{if(!supabase||!session)return;let live=true;supabase.from('items').select('data').order('updated_at',{ascending:false}).then(({data,error})=>{if(!live)return;if(error){setMessage(`No pudimos sincronizar todavía: ${error.message}. Tu copia de este dispositivo está segura.`);return;}const cloudItems=normalizeItems((data||[]).map(row=>row.data as Item));if(cloudItems.length)setItems(cloudItems);setCloudReady(true);});return()=>{live=false;};},[session]);
 const save=(next:Item[])=>{setItems(next);localStorage.setItem('mi-carril-items',JSON.stringify(next));if(supabase&&session&&cloudReady){const rows=next.map(item=>({id:item.id,owner_id:session.user.id,created_by:session.user.id,assigned_to:null,visibility:item.visibility==='SHARED'?'shared':item.visibility==='COACH_ASSIGNED'?'coach_assigned':'personal',title:item.title,status:item.status,data:item}));supabase.from('items').upsert(rows,{onConflict:'id'}).then(({error})=>{if(error)setMessage('Tu cambio quedó guardado localmente, pero aún no llegó a la nube.');});}};
 const update=(id:string,patch:Partial<Item>,action:string,note?:string)=>save(items.map(item=>item.id===id?{...item,...patch,updatedAt:new Date().toISOString(),events:[...item.events,{id:crypto.randomUUID(),at:new Date().toISOString(),action,note}]}:item));
 const start=(item:Item)=>{if(!item.nextAction?.trim())return setMessage('Define qué acción concreta mueve este asunto hacia adelante.');if(!canStart(items,item))return setMessage('Ya tienes 3 asuntos en ejecución. Elige cuál cerrar o bloquear antes de iniciar otro.');update(item.id,{status:'ACTIVE'},'Inició ejecución');};
 const lanes=active(items); const alerts=items.filter(item=>['OVERDUE_UNATTENDED','LATE_REPLAN','OVERDUE_TRACKED'].includes(timing(item))||item.status==='BLOCKED'); const rec=useMemo(()=>recommendation(items),[items]); const reminders=useMemo(()=>weekEntries(items),[items]);
 const filtered=items.filter(item=>screen==='Mi Carril'?item.gameRole==='QUARTERBACK'&&!['DONE','CANCELLED','INBOX','SOMEDAY'].includes(item.status):screen==='Proyectos'?item.kind==='PROJECT':labels[item.status]===screen);
 const backup=()=>{const blob=new Blob([JSON.stringify({format:'mi-carril-export',schemaVersion:2,appVersion:'0.2.0',exportedAt:new Date().toISOString(),items},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`accountability-partner-respaldo-${today}.json`;link.click();URL.revokeObjectURL(url);setMessage('Respaldo descargado.');};
 const restore=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));if(data.format!=='mi-carril-export'||!Array.isArray(data.items))throw new Error();if(!confirm(`Restaurar ${data.items.length} asuntos reemplazará la copia de este dispositivo. ¿Ya tienes un respaldo reciente?`))return;save(normalizeItems(data.items));setMessage('Respaldo restaurado correctamente.');}catch{setMessage('El archivo no parece ser un respaldo válido.');}};reader.readAsText(file);event.target.value='';};
 if(!authChecked)return <div className="authpage"><p>Preparando Accountability Partner…</p></div>; if(isSupabaseConfigured&&!session)return <SignIn/>;
 return <div className="shell"><aside><div className="brand">ACCOUNTABILITY<span>PARTNER</span><i>claridad · disciplina · avance</i></div><p className="navlabel">CENTRO DE MANDO</p>{['Comando','Mi Carril','Bandeja','Próximos','Esperando','Bloqueados'].map(x=><button className={screen===x?'nav on':'nav'} onClick={()=>setScreen(x)} key={x}>{x}</button>)}<p className="navlabel">DIRECCIÓN</p>{['Acuerdos','Proyectos','Métricas','Terminados','Acceso'].map(x=><button className={screen===x?'nav on':'nav'} onClick={()=>setScreen(x)} key={x}>{x}</button>)}</aside>
 <main><header><div><p className="eyebrow">TU TABLERO DE DIRECCIÓN</p><h1>{screen==='Semana'?'Semana próxima':screen}</h1></div><div className="headeractions">{session&&<span className="userbadge">{session.user.email}</span>}<button className="bell" onClick={()=>setScreen('Semana')}>🔔 <span>AVISOS</span>{reminders.length>0&&<b>{reminders.length}</b>}</button>{session&&<button className="backup" onClick={()=>supabase?.auth.signOut()}>SALIR</button>}<button className="backup" onClick={backup}>RESPALDAR</button><button className="backup" onClick={()=>backupInput.current?.click()}>RESTAURAR</button><input ref={backupInput} className="hidden" type="file" accept="application/json" onChange={restore}/><button className="capture" onClick={()=>setCapture(true)}>+ NUEVO ASUNTO</button></div></header>
 {message&&<div className="toast" onClick={()=>setMessage('')}>{message}</div>}
 {screen==='Comando'&&<><section className="hero"><div><p className="eyebrow">MISIÓN ACTUAL</p><h2>Construir libertad financiera sin sacrificar lo que sostiene tu vida.</h2><p>Una acción que mueve la misión. Un ritmo que puedes mantener.</p></div><div className="heroMark">AP<br/><span>01</span></div></section><section className="focus"><p>SIGUIENTE MOVIMIENTO</p>{rec?<><h2>{rec.title}</h2><span>{areaLabels[rec.area]} · {timingLabels[timing(rec)]}</span><strong>{rec.nextAction||'Define la siguiente acción.'}</strong><button onClick={()=>{start(rec);setScreen('Mi Carril')}}>INICIAR EJECUCIÓN</button></>:<p>No tienes prioridades activas.</p>}</section><div className="grid four"><Stat n={items.filter(i=>i.gameRole==='QUARTERBACK'&&i.status==='ACTIVE').length} t="Quarterbacks en ejecución"/><Stat n={items.filter(i=>i.status==='INBOX').length} t="Sin procesar"/><Stat n={items.filter(i=>i.status==='BLOCKED').length} t="Bloqueados formales"/><Stat n={items.filter(i=>timing(i)==='OVERDUE_UNATTENDED').length} t="Vencidos sin atención"/></div><section><div className="sectionhead"><h2>Radar de atención</h2><span>LO QUE EXIGE DECISIÓN</span></div>{alerts.length?alerts.map(i=><Card key={i.id} item={i} onClick={()=>setSelected(i)}/>):<Empty text="Todo está bajo control por ahora."/>}</section></>}
 {screen==='Mi Carril'&&<><p className="intro">Asuntos donde eres Quarterback: no tienes que hacer todo, pero sí consolidar el resultado.</p>{filtered.length?filtered.map(i=><Card key={i.id} item={i} onClick={()=>setSelected(i)}/>):<Empty text="Aún no hay asuntos donde seas Quarterback."/>}</>}
 {screen==='Métricas'&&<Metrics items={items}/>} {screen==='Acuerdos'&&<AgreementsBoard items={items} onClick={setSelected}/>} {screen==='Semana'&&<WeekCalendar entries={reminders} onClick={setSelected}/>} {screen==='Acceso'&&<AccessPanel/>}
 {!['Comando','Mi Carril','Métricas','Acuerdos','Semana','Acceso'].includes(screen)&&<section><p className="intro">{filtered.length} elemento{filtered.length===1?'':'s'}</p>{filtered.length?filtered.map(i=><Card item={i} key={i.id} onClick={()=>setSelected(i)}/>):<Empty text={`${screen} procesada. Nada necesita tu atención aquí.`}/>}</section>}
 </main>{capture&&<Capture draft={draft} setDraft={setDraft} onCancel={()=>setCapture(false)} onSave={area=>{if(draft.trim()){save([...items,make(draft.trim(),'INBOX',{area})]);setDraft('');setCapture(false);setMessage('Guardado en Bandeja.');}}}/>} {selected&&<Detail item={items.find(i=>i.id===selected.id)!} onClose={()=>setSelected(null)} onUpdate={update} onStart={start}/>}</div>;
}

function Stat({n,t}:{n:number,t:string}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Metrics({items}:{items:Item[]}){const all=items.filter(i=>!['INBOX','SOMEDAY','CANCELLED'].includes(i.status));const onTime=all.filter(i=>timing(i)==='ON_TIME').length;return <><div className="grid four"><Stat n={items.filter(i=>i.status==='DONE').length} t="Terminados"/><Stat n={onTime} t="En tiempo"/><Stat n={all.filter(i=>timing(i)==='RISK_INFORMED').length} t="Riesgo informado"/><Stat n={all.filter(i=>timing(i)==='OVERDUE_UNATTENDED').length} t="Vencidos sin atención"/></div><section className="metricsnote"><h2>Lectura de compromiso</h2><p>Amarillo: se avisó antes del vencimiento. Naranja: se reaccionó tarde. Rojo: venció sin atención registrada.</p></section></>}
function AgreementsBoard({items,onClick}:{items:Item[];onClick:(item:Item)=>void}){const open=items.filter(i=>!['DONE','CANCELLED','INBOX','SOMEDAY'].includes(i.status));const groups:[GameRole,string][]=[['QUARTERBACK','QUARTERBACKS'],['EXECUTOR','EJECUTORES'],['REFEREE','REFEREES'],['COACH','DT / COACH']];return <section><p className="intro">Cada rol tiene una responsabilidad distinta: consolidar, ejecutar, validar o desarrollar capacidad.</p><div className="agreementgrid">{groups.map(([role,title])=>{const group=open.filter(i=>i.gameRole===role);return <div className="agreementlane" key={role}><span>{title}</span>{group.length?group.map(i=><Card item={i} key={i.id} onClick={()=>onClick(i)}/>):<Empty text="Sin asuntos en este rol."/>}</div>})}</div></section>}
function WeekCalendar({entries,onClick}:{entries:CalendarEntry[];onClick:(item:Item)=>void}){const dates=Array.from({length:7},(_,i)=>dayAfter(today,i));return <section><p className="intro">Compromisos, reuniones y revisiones de los próximos siete días.</p><div className="weekgrid">{dates.map(date=>{const dayEntries=entries.filter(entry=>entry.date===date);const label=new Date(`${date}T12:00:00`).toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'});return <div className="daycolumn" key={date}><span>{label}</span>{dayEntries.length?dayEntries.map(entry=><button className={`calendarentry ${entry.mode.toLowerCase()}`} key={`${entry.item.id}-${entry.mode}`} onClick={()=>onClick(entry.item)}><small>{entry.mode==='COMPROMISO'?'COMPROMISO':entry.mode==='REUNION'?'REUNIÓN':'SEGUIMIENTO'}</small><b>{entry.item.title}</b>{entry.item.person&&<em>Responsable: {entry.item.person}</em>}</button>):<p>Sin compromisos.</p>}</div>})}</div></section>}
function Card({item,onClick}:{item:Item;onClick:()=>void}){const state=timing(item);return <button className={`card timing-${state.toLowerCase()}`} onClick={onClick}><div><small>{item.gameRole?gameRoleLabels[item.gameRole]:'Sin rol'} · {item.priority}</small><h3>{item.title}</h3>{item.nextAction&&<p>{item.nextAction}</p>}</div><div className="meta"><span className={`timing timing-${state.toLowerCase()}`}>{timingLabels[state]}</span>{item.dueDate&&<span>{item.dueDate===today?'Vence hoy':`Entrega ${item.dueDate}`}</span>}</div></button>}
function Capture({draft,setDraft,onCancel,onSave}:{draft:string;setDraft:(x:string)=>void;onCancel:()=>void;onSave:(area:LifeArea)=>void}){const [area,setArea]=useState<LifeArea>('MISSION');return <div className="overlay"><div className="modal capturemodal"><button className="close" onClick={onCancel}>×</button><p className="eyebrow">CAPTURA RÁPIDA</p><h2>¿Qué necesita atención?</h2><textarea autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Ej. Revisar diferencias de inventario con Azucena."/><label>Área<select value={area} onChange={e=>setArea(e.target.value as LifeArea)}>{Object.entries(areaLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="primary" onClick={()=>onSave(area)}>GUARDAR EN BANDEJA</button></div></div>}
function SignIn(){const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [error,setError]=useState('');const send=async()=>{if(!supabase||!email.trim())return;const {error:loginError}=await supabase.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:window.location.href}});if(loginError)setError(loginError.message);else setSent(true);};return <div className="authpage"><div className="authcard"><div className="brand dark">ACCOUNTABILITY<span>PARTNER</span><i>claridad · disciplina · avance</i></div><h1>Tu centro de dirección</h1>{sent?<p>Revisa tu correo y abre el enlace de acceso.</p>:<><p>Entra para conservar tu dirección y trabajar desde cualquier dispositivo.</p><label>Tu correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@correo.com"/></label>{error&&<p className="autherror">{error}</p>}<button className="primary" onClick={send}>ENVIAR ENLACE DE ACCESO</button></>}</div></div>}
function AccessPanel(){return <section className="accesspanel"><p className="eyebrow">PRIVACIDAD Y ACOMPAÑAMIENTO</p><h2>Tu vida completa no es el tablero de nadie.</h2><p>El coach de negocio verá únicamente los asuntos que decidas compartir.</p><div className="accessgrid"><div><b>ACCESO DEL COACH</b><strong>Profesional, negocio y libertad financiera</strong><strong>Aprendizaje y formación</strong></div><div className="locked"><b>PRIVADO PARA TI</b><strong>Salud y energía</strong><strong>Relaciones y familia</strong><strong>Bienestar, propósito y espiritualidad</strong></div></div></section>}

function Detail({item,onClose,onUpdate,onStart}:{item:Item;onClose:()=>void;onUpdate:(id:string,p:Partial<Item>,a:string,n?:string)=>void;onStart:(i:Item)=>void}){
 const [draft,setDraft]=useState<Item>(item); const [note,setNote]=useState(''); const [showBlock,setShowBlock]=useState(item.status==='BLOCKED'); const [showReplan,setShowReplan]=useState(false);
 useEffect(()=>setDraft(item),[item]);
 const set=(patch:Partial<Item>)=>setDraft(value=>({...value,...patch}));
 const saveDetails=()=>{const patch:Partial<Item>={...draft};delete patch.id;delete patch.events;delete patch.createdAt;delete patch.updatedAt;if(draft.dueDate&&!item.originalDueDate)patch.originalDueDate=draft.dueDate;onUpdate(item.id,patch,'Detalles del asunto actualizados');};
 const formalBlock=()=>{if(!draft.blocker?.trim()||!draft.escalatedTo?.trim()||!draft.escalatedAt||!draft.escalationMethod?.trim()||!draft.escalationMessage?.trim()||!draft.requestedSupport?.trim()||!draft.escalationReviewDate){alert('Para bloquear formalmente falta causa, superior informado, fecha, medio, mensaje, apoyo solicitado y fecha de revisión.');return;}onUpdate(item.id,{...draft,status:'BLOCKED'},'Bloqueo formal escalado',note||draft.blocker);setShowBlock(false);};
 const requestReplan=()=>{if(!draft.requestedDueDate||!draft.replanReason||!draft.replanNote?.trim()||!draft.replanNotifiedTo?.trim()||!draft.replanMethod?.trim()){alert('Para solicitar cambio de fecha falta nueva fecha, razón, explicación y a quién/por qué medio avisaste.');return;}onUpdate(item.id,{requestedDueDate:draft.requestedDueDate,replanReason:draft.replanReason,replanNote:draft.replanNote,replanNotifiedTo:draft.replanNotifiedTo,replanMethod:draft.replanMethod,replanImpact:draft.replanImpact,replanRequestedAt:new Date().toISOString(),replanStatus:'PENDING'},'Solicitud de replaneación enviada',draft.replanNote);setShowReplan(false);};
 const approveReplan=()=>{if(!item.requestedDueDate)return;onUpdate(item.id,{dueDate:item.requestedDueDate,replanStatus:'APPROVED'},'Nueva fecha aprobada',`Compromiso actualizado a ${item.requestedDueDate}.`);};
 const relevant=item.events.filter(event=>!['Área actualizada','Privacidad actualizada','Tipo actualizado','Personas involucradas actualizadas','Responsable actualizado','Prioridad actualizada','Siguiente acción actualizada'].includes(event.action));
 return <div className="overlay"><div className="modal detailmodal"><button className="close" onClick={onClose}>×</button><small>{labels[item.status]} · {timingLabels[timing(item)]}</small><h2>{item.title}</h2>
 <div className="formgrid"><label>Rol en la jugada<select value={draft.gameRole||''} onChange={e=>set({gameRole:(e.target.value||undefined) as GameRole|undefined})}><option value="">Aún sin rol</option>{Object.entries(gameRoleLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Tipo<select value={draft.kind} onChange={e=>set({kind:e.target.value as Kind})}>{Object.entries(kindLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Área<select value={draft.area} onChange={e=>set({area:e.target.value as LifeArea})}>{Object.entries(areaLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Prioridad<select value={draft.priority} onChange={e=>set({priority:e.target.value as Priority})}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label></div>
 <label>Responsable de entregar<input value={draft.person||''} onChange={e=>set({person:e.target.value})} placeholder="Nombre de quien debe entregar"/></label><label>Personas involucradas<input value={draft.participants||''} onChange={e=>set({participants:e.target.value})} placeholder="Ej. Compras, Logística, Sol"/></label><label>Mi función<input value={draft.role||''} onChange={e=>set({role:e.target.value})} placeholder="Ej. Dirección General"/></label><div className="formgrid"><label>Fecha compromiso actual<input type="date" value={draft.dueDate||''} onChange={e=>set({dueDate:e.target.value||undefined})}/></label><label>Próximo seguimiento<input type="date" value={draft.reviewDate||''} onChange={e=>set({reviewDate:e.target.value||undefined})}/></label><label>Próxima reunión<input type="datetime-local" value={draft.meetingAt||''} onChange={e=>set({meetingAt:e.target.value||undefined})}/></label></div>
 <label>Siguiente acción<input value={draft.nextAction||''} onChange={e=>set({nextAction:e.target.value})} placeholder="Una acción concreta que mueve el asunto"/></label><label>Depende de / posible bloqueo<input value={draft.blocker||''} onChange={e=>set({blocker:e.target.value})} placeholder="Ej. autorización de compra o información de logística"/></label><button className="primary" onClick={saveDetails}>GUARDAR DATOS DEL ASUNTO</button>
 {item.status==='INBOX'&&<div className="actions"><button onClick={()=>onUpdate(item.id,{status:'NEXT'},'Procesado y enviado a Próximos')}>DEFINIR DESPUÉS</button><button onClick={()=>onUpdate(item.id,{status:'SOMEDAY'},'Guardado como idea')}>ES IDEA</button></div>}
 {['NEXT','BLOCKED'].includes(item.status)&&<button className="primary" onClick={()=>onStart({...item,nextAction:draft.nextAction})}>{item.status==='BLOCKED'?'DESBLOQUEAR E INICIAR':'INICIAR EJECUCIÓN'}</button>}
 {item.status==='DONE'&&<button className="primary" onClick={()=>onUpdate(item.id,{status:'NEXT'},'Reactivado y enviado a Próximos')}>REACTIVAR</button>}
 {!['DONE','CANCELLED','INBOX','SOMEDAY'].includes(item.status)&&<div className="actions"><button onClick={()=>setShowReplan(!showReplan)}>SOLICITAR CAMBIO DE FECHA</button>{item.replanStatus==='PENDING'&&<button onClick={approveReplan}>APROBAR NUEVA FECHA</button>}</div>}
 {showReplan&&<section className="subform"><h3>Solicitud de replaneación</h3><p>La fecha original no se borra. Esta solicitud queda registrada y debe ser aprobada.</p><label>Nueva fecha solicitada<input type="date" value={draft.requestedDueDate||''} onChange={e=>set({requestedDueDate:e.target.value})}/></label><label>Razón<select value={draft.replanReason||''} onChange={e=>set({replanReason:e.target.value as ReplanReason})}><option value="">Elige la razón</option>{Object.entries(replanReasonLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Explicación<input value={draft.replanNote||''} onChange={e=>set({replanNote:e.target.value})} placeholder="Qué ocurrió y qué harás para cumplir"/></label><label>Superior informado<input value={draft.replanNotifiedTo||''} onChange={e=>set({replanNotifiedTo:e.target.value})}/></label><label>Medio de aviso<input value={draft.replanMethod||''} onChange={e=>set({replanMethod:e.target.value})} placeholder="WhatsApp, correo, reunión…"/></label><label>Impacto en otras áreas<input value={draft.replanImpact||''} onChange={e=>set({replanImpact:e.target.value})}/></label><button onClick={requestReplan}>REGISTRAR SOLICITUD</button></section>}
 {item.status==='ACTIVE'&&<><div className="actions"><button onClick={()=>setShowBlock(!showBlock)}>DECLARAR BLOQUEO</button><button onClick={()=>onUpdate(item.id,{status:'DONE'},'Resultado terminado',note)}>TERMINAR</button></div><label>Nota de avance o acuerdo<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Qué pasó, qué sigue y quién queda responsable"/></label><button onClick={()=>{if(!note.trim())return alert('Escribe una nota de avance antes de registrarla.');onUpdate(item.id,{progress:item.kind==='PROJECT'?Math.min(100,(item.progress||0)+10):item.progress},'Avance registrado',note);setNote('');}}>REGISTRAR AVANCE</button></>}
 {showBlock&&<section className="subform"><h3>Bloqueo formal</h3><p>Un bloqueo exige causa, escalamiento y fecha de seguimiento. Así nadie puede dejar un asunto detenido sin avisar.</p><label>Causa del bloqueo<select value={draft.blockerCategory||''} onChange={e=>set({blockerCategory:e.target.value as BlockerCategory})}><option value="">Elige la causa</option>{Object.entries(blockerLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Qué impide avanzar<input value={draft.blocker||''} onChange={e=>set({blocker:e.target.value})}/></label><label>Jefe inmediato / superior<input value={draft.directManager||''} onChange={e=>set({directManager:e.target.value})}/></label><label>A quién se escaló<input value={draft.escalatedTo||''} onChange={e=>set({escalatedTo:e.target.value})}/></label><label>Fecha y hora de aviso<input type="datetime-local" value={draft.escalatedAt?.slice(0,16)||''} onChange={e=>set({escalatedAt:e.target.value?new Date(e.target.value).toISOString():undefined})}/></label><label>Medio de aviso<input value={draft.escalationMethod||''} onChange={e=>set({escalationMethod:e.target.value})} placeholder="WhatsApp, llamada, correo, reunión…"/></label><label>Mensaje / resumen informado<textarea value={draft.escalationMessage||''} onChange={e=>set({escalationMessage:e.target.value})}/></label><label>Apoyo solicitado<input value={draft.requestedSupport||''} onChange={e=>set({requestedSupport:e.target.value})} placeholder="Decisión, presupuesto, apoyo, formación…"/></label><label>Fecha para revisar respuesta<input type="date" value={draft.escalationReviewDate||''} onChange={e=>set({escalationReviewDate:e.target.value})}/></label><button onClick={formalBlock}>REGISTRAR BLOQUEO FORMAL</button></section>}
 {item.kind==='PROJECT'&&<label>Progreso<input type="number" min="0" max="100" value={draft.progress??0} onChange={e=>set({progress:Number(e.target.value)})}/></label>}
 <h3>Historial relevante</h3><div className="timeline">{relevant.length?[...relevant].reverse().map(event=><p key={event.id}><b>{new Date(event.at).toLocaleString('es-MX')}</b>{event.action}{event.note&&`: ${event.note}`}</p>):<p>Aún no hay eventos relevantes.</p>}</div></div></div>;
}
